# Practica Basica Numpy

In [ ]:
import numpy as np

In [ ]:
lista=[1,2,3,4,5,6,7,8,9]

El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a traves del indexado, a un dato específico o un grupo de muchos datos específicos.

In [ ]:
# Llevar una lista de python a un array de numpy
arr = np.array(lista)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Generar un matriz en Numpy

In [ ]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Indexado Arrays y Matrices

El indexado nos permite acceder a los elementos de los array y matrices
Los elementos se emepiezan a contar desde 0.

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0]

1

Es posible operar directamente con los elementos.

In [ ]:
arr[0] + arr[5]

7

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

En el caso de las matrices al indezar una posición se regresa el array de dicha posición.

In [ ]:
matriz[0]

array([1, 2, 3])

Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.

In [ ]:
matriz[0,2]

3

## Slicing

El slicing nos permite extraer varios datos, tiene un comienzo y un final.

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

En este ejemplo se está extrayendo datos desde la posición 0 hasta la 5. [1:6].

In [ ]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

Si no se ingresa el valor de Start se toma el incio como la posición 0.

In [ ]:
arr[:6] #Puntos al comienzo significa que comience en el inicio hasta el punto de referencia final (en este caso el Nro 6)

array([1, 2, 3, 4, 5, 6])

En cambio si no se le da una posción de End se regresan todos los elementos hasta el final del array.

In [ ]:
arr[2:] #Puntos al final significa que vaya hasta el final teniendo en cuenta la referencia de inicio (en este caso el Nro 2)

array([3, 4, 5, 6, 7, 8, 9])

También se puede trabajar por pasos.
En este ejemplo de 3 en 3.
Regresa la posición 0, 0 + 3, 3 + 3 y como no hay posición 6 + 3, no se regrese nada.

In [ ]:
arr[::3] #Toma los elementos de 3 en 3. 

array([1, 4, 7])

Cuando se le asigna un valor negativo se regresan los valores comenzando desde la última posición del array.

In [ ]:
arr[-1] # Toma el primer valor pero del final

9

In [ ]:
arr[-3:] # Toma los ultimos 3 valores

array([7, 8, 9])

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Para el caso de las matrices sucede algo similar.
Para acceder a los valores a nivel de filas.

In [ ]:
matriz[1:] #Tomar la matriz desde la fila 1.

array([[4, 5, 6],
       [7, 8, 9]])

Para acceder a los valores a nivel de filas y columnas.

In [ ]:
matriz[1:,0:2] #Tomar todas las filas a partir de la 1 y solo las columna 0 y 1. 

array([[4, 5],
       [7, 8]])

In [ ]:
matriz[:,2] # Tomar ultima columna

array([3, 6, 9])